sudo: false

language: go

go:
  - 1.6

install:
  - go get gopkg.in/jarcoal/httpmock.v1
  - go get github.com/sbstjn/hanu
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci

branches:
  only:
    - master
